"""Rung 6 (last resort): HTML scraper base.

Rules enforced here, not left to generated subclasses:
  - robots.txt is checked before every request; disallowed paths raise RobotsDisallowed
  - a minimum delay between requests (scraper.min_delay_s)
  - a hard cap on pages per run (scraper.max_pages_per_run)
  - the configured user agent identifies every request
Concrete scrapers live in adapters/generated/ (written by self-heal only) and
are created with status 'pending_approval'; the runner refuses to execute them
until approved via --approve.
"""
from __future__ import annotations

import time
import urllib.robotparser
from typing import Iterator, Optional
from urllib.parse import urljoin, urlparse

from core.config import Config
from core.http import Http
from core.log import get_logger
from core.models import SourceRecord, TargetRecord

from .base import BaseAdapter

log = get_logger("adapter.scraper")


class RobotsDisallowed(Exception):
    pass


class PageCapExceeded(Exception):
    pass


class ScraperBase(BaseAdapter):
    def __init__(self, layer: str, target: TargetRecord, source: SourceRecord, cfg: Config):
        super().__init__(layer, target, source, cfg)
        self.user_agent = str(cfg.get("scraper.user_agent"))
        self.min_delay_s = float(cfg.get("scraper.min_delay_s"))
        self.max_pages = int(cfg.get("scraper.max_pages_per_run"))
        self.respect_robots = bool(cfg.get("scraper.respect_robots_txt"))
        self.http = Http.from_config(cfg, user_agent=self.user_agent)
        self._pages_fetched = 0
        self._last_request_at: Optional[float] = None
        self._robots_cache: dict[str, urllib.robotparser.RobotFileParser] = {}

    # -- enforced request path: generated scrapers must use get_page() --
    def _robots_allows(self, url: str) -> bool:
        if not self.respect_robots:
            return True
        origin = "{0.scheme}://{0.netloc}".format(urlparse(url))
        rp = self._robots_cache.get(origin)
        if rp is None:
            rp = urllib.robotparser.RobotFileParser()
            try:
                txt = self.http.get_text(urljoin(origin, "/robots.txt"))
                rp.parse(txt.splitlines())
            except Exception:
                rp.parse([])  # unreachable robots.txt -> allow
            self._robots_cache[origin] = rp
        return rp.can_fetch(self.user_agent, url)

    def _throttle(self) -> None:
        if self._last_request_at is not None:
            elapsed = time.monotonic() - self._last_request_at
            if elapsed < self.min_delay_s:
                time.sleep(self.min_delay_s - elapsed)
        self._last_request_at = time.monotonic()

    def get_page(self, url: str, params: Optional[dict] = None) -> str:
        if self._pages_fetched >= self.max_pages:
            raise PageCapExceeded(
                f"scraper page cap ({self.max_pages}) reached for {self.target.id}/{self.layer}")
        if not self._robots_allows(url):
            raise RobotsDisallowed(f"robots.txt disallows {url} for {self.user_agent!r}")
        self._throttle()
        self._pages_fetched += 1
        return self.http.get_text(url, params=params)

    # -- extraction helpers for generated scrapers --
    @staticmethod
    def soup(html: str):
        from bs4 import BeautifulSoup
        return BeautifulSoup(html, "lxml")

    @staticmethod
    def html_tables(html: str) -> list[list[dict]]:
        """Every <table> as a list of {header: cell} dicts (first row = headers)."""
        from bs4 import BeautifulSoup
        out: list[list[dict]] = []
        for table in BeautifulSoup(html, "lxml").find_all("table"):
            rows = table.find_all("tr")
            if not rows:
                continue
            headers = [c.get_text(strip=True) for c in rows[0].find_all(["th", "td"])]
            body = []
            for tr in rows[1:]:
                cells = [c.get_text(strip=True) for c in tr.find_all("td")]
                if cells:
                    body.append(dict(zip(headers, cells)))
            out.append(body)
        return out

    def fetch(self, target: TargetRecord, source: SourceRecord, cfg: Config,
              max_rows: int | None = None) -> Iterator[dict]:
        raise NotImplementedError("concrete scrapers are generated by self-heal")
