"""Sources registry: file-first (config/sources.yaml, GENERATED — never
hand-edited) with optional Postgres sync when DATABASE_URL is configured.

The yaml file is the source of truth for discover/dry-run so the pipeline works
before a database exists; the runner syncs it into the `sources` table when a
DB is available and keeps statuses in both places.
"""
from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path
from typing import Optional

import yaml

from .config import Config
from .log import get_logger
from .models import SourceRecord, TargetRecord

log = get_logger("registry")


class Registry:
    def __init__(self, cfg: Config):
        self.cfg = cfg
        self.sources_path = cfg.path("sources_file")
        self.data: dict = {"counties": [], "jurisdictions": [], "sources": []}
        if self.sources_path.exists():
            with open(self.sources_path, "r", encoding="utf-8") as fh:
                self.data = yaml.safe_load(fh) or self.data

    # ---------- file side ----------
    def save(self) -> None:
        self.sources_path.parent.mkdir(parents=True, exist_ok=True)
        fd, tmp = tempfile.mkstemp(dir=str(self.sources_path.parent), suffix=".tmp")
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as fh:
                fh.write("# GENERATED by core.discover — do not hand-edit.\n")
                yaml.safe_dump(self.data, fh, sort_keys=False, allow_unicode=True)
            os.replace(tmp, self.sources_path)
        except BaseException:
            if os.path.exists(tmp):
                os.unlink(tmp)
            raise

    @property
    def counties(self) -> list[dict]:
        return self.data.setdefault("counties", [])

    @property
    def jurisdictions(self) -> list[dict]:
        return self.data.setdefault("jurisdictions", [])

    def targets_by_id(self) -> dict[str, TargetRecord]:
        out: dict[str, TargetRecord] = {}
        for c in self.counties:
            out[c["fips"]] = TargetRecord(
                id=c["fips"], kind="county", fips=c["fips"], name=c["name"],
                state=c["state"], state_fips=c["state_fips"], bbox=c.get("bbox"),
                geom_wkt=c.get("geom_wkt"))
        for j in self.jurisdictions:
            out[j["id"]] = TargetRecord(
                id=j["id"], kind=j["kind"], fips=j["fips"], name=j["name"],
                state=j["state"], state_fips=j.get("state_fips", ""), bbox=j.get("bbox"),
                geom_wkt=j.get("geom_wkt"))
        return out

    def sources(self) -> list[SourceRecord]:
        return [SourceRecord.from_dict(s) for s in self.data.get("sources", [])]

    def get_source(self, target_id: str, layer: str) -> Optional[SourceRecord]:
        for s in self.data.get("sources", []):
            if s["target_id"] == target_id and s["layer"] == layer:
                return SourceRecord.from_dict(s)
        return None

    def upsert_source(self, rec: SourceRecord) -> None:
        rows = self.data.setdefault("sources", [])
        for i, s in enumerate(rows):
            if s["target_id"] == rec.target_id and s["layer"] == rec.layer:
                rows[i] = rec.to_dict()
                return
        rows.append(rec.to_dict())

    def rung_histogram(self) -> dict[str, dict[str, int]]:
        hist: dict[str, dict[str, int]] = {}
        for s in self.data.get("sources", []):
            layer = s["layer"]
            rung = s.get("rung") or ("discovery_mode" if s.get("discovery_mode") else "none")
            hist.setdefault(layer, {})
            hist[layer][rung] = hist[layer].get(rung, 0) + 1
        return hist

    # ---------- DB side (optional) ----------
    def sync_to_db(self, conn) -> None:
        with conn.cursor() as cur:
            for c in self.counties:
                cur.execute(
                    """INSERT INTO counties (fips, state, name, population, rank, bbox)
                       VALUES (%s, %s, %s, %s, %s,
                               CASE WHEN %s IS NULL THEN NULL ELSE ST_MakeEnvelope(%s,%s,%s,%s,4326) END)
                       ON CONFLICT (fips) DO UPDATE SET
                         population = EXCLUDED.population, rank = EXCLUDED.rank,
                         bbox = EXCLUDED.bbox""",
                    (c["fips"], c["state"], c["name"], c.get("population"), c.get("rank"),
                     (c.get("bbox") or [None])[0], *((c.get("bbox") or [0, 0, 0, 0])[:4])))
            for j in self.jurisdictions:
                cur.execute(
                    """INSERT INTO jurisdictions (id, fips, name, kind, geom)
                       VALUES (%s, %s, %s, %s, ST_Multi(ST_GeomFromText(%s, 4326)))
                       ON CONFLICT (id) DO UPDATE SET
                         name = EXCLUDED.name, kind = EXCLUDED.kind,
                         geom = COALESCE(EXCLUDED.geom, jurisdictions.geom)""",
                    (j["id"], j["fips"], j["name"], j["kind"], j.get("geom_wkt")))
            for s in self.data.get("sources", []):
                cur.execute(
                    """INSERT INTO sources (target_id, layer, rung, source_url, adapter_module,
                                            status, last_error, rewrite_count, rungs_tried)
                       VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
                       ON CONFLICT (target_id, layer) DO UPDATE SET
                         rung = EXCLUDED.rung, source_url = EXCLUDED.source_url,
                         adapter_module = EXCLUDED.adapter_module, status = EXCLUDED.status,
                         last_error = EXCLUDED.last_error,
                         rewrite_count = EXCLUDED.rewrite_count,
                         rungs_tried = EXCLUDED.rungs_tried
                       RETURNING id""",
                    (s["target_id"], s["layer"], s.get("rung"), s.get("source_url"),
                     s.get("adapter_module"), s.get("status", "pending"),
                     s.get("last_error"), s.get("rewrite_count", 0),
                     json.dumps(s.get("rungs_tried") or {})))
                s["id"] = cur.fetchone()[0]
        conn.commit()

    def approve(self, source_id: str) -> Optional[SourceRecord]:
        """Flip a pending_approval source (matched by '<target_id>/<layer>' or DB id) to pending."""
        for s in self.data.get("sources", []):
            key = f"{s['target_id']}/{s['layer']}"
            if (key == source_id or str(s.get("id")) == str(source_id)) \
                    and s.get("status") == "pending_approval":
                s["status"] = "pending"
                self.save()
                return SourceRecord.from_dict(s)
        return None
